### ISSUE TITLE
Problem with "Undefined function or variable 'gcbs'"

### ISSUE THREAD

**Issue by zyfff123456** [McSCert/Reach-Coreach#2]
Hello! When I was using the tool, I found an error,"Undefined function or variable 'gcbs'",as shown below.
error eval
Undefined function or variable 'gcbs'。

 sl_customization>RCRReachCallback (line 71)
                    eval([bdroot(gcs) '_reachCoreachObject.reachAll(gcbs, gcls);']);
I wonder if a configuration is missing or something else?

**Comment by monikajaskolka** [comment]
Do you have the [Simulink Utility](https://github.com/McSCert/Simulink-Utility) downloaded and on your Matlab path? The `gcbs` function is provided by this utility [here](https://github.com/McSCert/Simulink-Utility/tree/master/GetCurrentFunctions). Please read the [User Guide](https://github.com/McSCert/Reach-Coreach/blob/master/doc/ReachCoreach_UserGuide.pdf) as it mentions this dependency in Section 2.1, item  3.

**Comment by zyfff123456** [comment]
Thank you,it works.
